### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by Felixkxy** [Felixkxy/chat-space#13]
# IPアドレス
http://18.179.217.76/

**Comment by mo1015** [comment]
孔さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！



**○サイドバーの「グループ名」、「最新メッセージ」に入っている下線を消しましょう
○サイドバーの背景色を見本と同じにしましょう**

<img width="1440" alt="修正" src="https://user-images.githubusercontent.com/62644781/85944399-5b27cf00-b971-11ea-9321-7d11a38b0eea.png">

↓参考カリキュラム
<img width="840" alt="スクリーンショット 2020-06-25 15 44 57" src="https://user-images.githubusercontent.com/62644781/85944378-329fd500-b971-11ea-91fa-1cde36981063.png">


修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by Felixkxy** [comment]
ご確認ありがとうございます。
下記修正しましたので、改めてご確認をお願い致します。

**- [✓] サイドバーの「グループ名」、「最新メッセージ」に入っている下線を消しましょう**
　_message.scssでaタグ全体の下線を消しました。下記スクショは選択した状態で取りましたので、下線がなくなったことが確認できます。

**- [✓] サイドバーの背景色を見本と同じにしましょう**
　こちら単純に色を間違えましたので修正しました。

![スクリーンショット 2020-06-28 20 10 33](https://user-images.githubusercontent.com/34212372/85945859-7566aa80-b97b-11ea-985c-896029a1cc5e.png)

**Comment by yasunamiura** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
※今後実装に関する質問がありましたら、メンターに確認をお願いします！
